### ISSUE TITLE
How conditional usage is handled?

### ISSUE THREAD

**Issue by larsbs** [sw-yx/babel-blade#21]
Hi, really awesome and promising library. I'm really tempted to use it on some side projects to see if we can start introducing it into our production code but I have a doubt that I haven't seen in the docs.

How does it handle conditional use cases? I guess tracking the used properties of an object is "easy" but how does it detect properties that might not be used and that depends on data being already present? For example:

```javascript
import { Connect, query } from 'urql';
import { createQuery } from 'blade.macro'; // if you are using as a babel macro

const movieQuery = createQuery(); // create the query
const Movie = () => (
  <div>
    <Connect
      query={query(movieQuery)}
      children={({ data }) => {
        const DATA = movieQuery(data); // `DATA` is a blade
        const { schedule } = DATA; // `schedule` is also a blade
        return (
          <div>
            <h2>{schedule.movie}</h2>
            {schedule.hasDetails ? <pre>{schedule.details}</pre> : null}{/* Without having the value of has Details, how does it knows we also have to add .details? */}
          </div>
        );
      }}
    />
  </div>
);
```

And how usage in subcomponents is handled? If I pass `schedule` to `children`, and inside one of the children components, I do `schedule.hours`, would that also be caught by the macro?

**Comment by jgierer12** [comment]
It will always add `schedule.details` to the query. Imagine if you wrote this query yourself - you also wouldn't be able to include or exclude a field depending on the value of another field so you will always have to include the "optional" fields.

Fields in sub components won't be caught, because babel itself doesn't resolve dependencies. But you can use a [fragment](https://babel-blade.netlify.com/docs/graphql-spec#fragments) to add a child's query to the main one.

**Comment by sw-yx** [comment]
Jonas is right on both details. note that you can always test your questions inside of Astexplorer.net or the Babeljs.io REPL to see how it would transform :)

thanks for trying! feel free to ask more questions, am closing for now
