### ISSUE TITLE
Typescript Auto-completion

### ISSUE THREAD

**Issue by williamluke4** [sw-yx/babel-blade#26]
## DX Heaven

I have no idea if this would work or if this would be possible. 

Basic thoughts are to use the graphql schema to generate TS defs for all the queries then use this to provide typedefs for the Auto-completion.

Basically a marriage of https://github.com/dotansimha/graphql-code-generator and babel-blade.

**Comment by williamluke4** [comment]
Is anyone willing to help out with this or at least point me in the right direction?

**Comment by ForsakenHarmony** [comment]
Doing this in `babel-blade` right now it seems non trivial, potentially a lot of work, given that `babel-blade` is not aware of the graphql schema

With `graphql-code-generator` it's probably a bit easier

You'd want to generate a definition for the module `babel-plugin-blade/macro` 
Something along the lines of 

```ts
declare module "babel-plugin-blade/macro" {
    type Query = { /* ...... */ };
    type QueryCreator = string & ((data: any) => Query);
    function createQuery(): QueryCreator;
}
```

With `Query` being what you get from the default typescript generation thing

But there might be issues with nullable fields in the typescript def

It's also not the cleanest, because it has to be a string and a function at the same time

**Comment by williamluke4** [comment]
Is there a mock schema that you use for the fixtures?

**Comment by swyxio** [comment]
there was a point in the past when i considered rewriting babel blade as a typescript plugin, just to get ts autocomplete. it wasnt very popular so i dropped the idea. the other way people are getting around this is running a type generation service while people are authoring, and importing that type in. probably more trouble than it is worth, just use `any`.

**Comment by williamluke4** [comment]
@sw-yx I do think that if Autocompeltion is added then this would definitely become popular. I really think that it would provide one of the best DXs for data fetching.

**Comment by williamluke4** [comment]
Closing due to lack off time and energy :)

**Comment by swyxio** [comment]
np :) i think gqless did it somehow if you ever want to look
